---
- name: Configuring Apache HTTPD
  hosts: web
  become: true
  tasks:

    - name: Ensuring httpd package presence
      yum:
        name: httpd
        state: present    #latest
      when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    
    - name: Copying index.html
      copy:
        src: ./files/index.html          #./files/
        dest: /var/www/html/index.html   #/var/www/html/
        mode: preserve

    - name: Starting httpd
      service:         
        name: httpd
        state: started
        enabled: true

    - name: Configuring firewalld to allow http service
      firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true

    - name: firewalld enabled and running
      service:
        name: firewalld
        state: restarted
        enabled: true

- name: Testing connectivity
  hosts: localhost
  tasks:

    - name: Connecting to webserver
      uri:
        url: http://192.168.1.10:80/index.html
        return_content: yes
        status_code: 200
...
